# ===== Fonte =====
font_family FiraCode Nerd Font
font_size 12.0
bold_font auto
italic_font auto

# ===== Transparência =====
background_opacity 0.85
foreground   #d8dee9
cursor       #88c0d0
cursor_shape block

# ===== Bordas e scroll =====
active_tab_background   #3b4252
inactive_tab_background #2e3440
scrollback_lines 10000

# ===== Bell =====
enable_audio_bell no
visual_bell duration 0.1 color #bf616a

# ===== Cores Nord =====
color0  #3b4252
color1  #bf616a
color2  #a3be8c
color3  #ebcb8b
color4  #81a1c1
color5  #b48ead
color6  #88c0d0
color7  #e5e9f0
color8  #4c566a
color9  #bf616a
color10 #a3be8c
color11 #ebcb8b
color12 #81a1c1
color13 #b48ead
color14 #8fbcbb
color15 #eceff4
